[application]
tailwind_input = "tailwind.css"
tailwind_output = "assets/web.css"

[web.wasm_opt]
level = "z"
debug = false
keep_names = false
memory_packing = true
extra_features = ["--converge"]

[web]
pre_compress = true
resource_strategy = "aggressive"
